---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio
    - name: nopasswdlogin
      must_exist: false
      system: true
sudoersGroup:    wheel
autologinGroup:  autologin
sudoersConfigureWithGroup: false
setRootPassword: true
doReusePassword: false
displayAutologin:   false
doAutologin:     false
passwordRequirements:
    minLength: -1
    maxLength: -1
    libpwquality:
        - minlen=8
        - minclass=2
allowWeakPasswords: true
allowWeakPasswordsDefault: false
user:
  shell: /bin/zsh
  forbidden_names: [ root ]
  home_permissions: "o700"
  nopasswd_group: "nopasswdlogin"
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "forge-os"
  forbidden_names: [ localhost ]
allowActiveDirectory: false
presets:
    fullName:
        editable: true
    loginName:
        editable: true
